  <!--
    MAIN AUTHOR: Justin P.
    Comments/Formatting done by: Justin P.
  -->

<!DOCTYPE html>
<html lang="en">
  <head>
      <!-- Tab title -->
    <title>Discussion Group Generator</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="css/animate.css">  
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">
    <link rel="stylesheet" href="css/magnific-popup.css">
    <link rel="stylesheet" href="css/aos.css">
    <link rel="stylesheet" href="css/ionicons.min.css">
    <link rel="stylesheet" href="css/flaticon.css">
    <link rel="stylesheet" href="css/icomoon.css">
    <link rel="stylesheet" href="css/style.css">
  </head>

    <!-- Navigation button and a signout button -->
  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
    <br>  
    <a href="faculty_homepage.php" class="btn btn-primary" style="position: absolute; margin-left:50px;">Back to Home</a>
	<a href="signout.php" class="btn btn-primary" style="position: absolute; margin-left:1100px;">Sign Out</a>
	<section class="hero-wrap js-fullheight">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight justify-content-center align-items-center">
                <div class="col-lg-8 col-md-6 ftco-animate d-flex align-items-center">

                    <?php
                            // Connects to the database and stores the result of the query into a variable
                        $conn = mysqli_connect('localhost', 'justin', 'welcome', 'seniorProject');
                        $query = "select classId, className, approved from classes where approved != 0 ";
                        $result = $conn->query($query);

                            // If there is a result, then the class of the result is displayed
                        if ($result->num_rows > 0)
                        {
                                // If the algorithm had been implemented, this would be slightly different
                                // but the end result is the same. Here the groups that were generated by the
                                // algorithm would have printed out here to the professor. For now the groups
                                // are randomly picked
                            echo '<div class="text text-center">';
                            echo '<h2>Here are the groups for the approved classes.</h2>';
                          while($class = $result->fetch_assoc())
                          {
                                // Class of approved groups
                            echo '<br><br><h2>'.$class['className'].' ('.$class['classId'].')</h2>';

                              // Tracks group number and students in a group
                            $groupNum = 1;
                            
                              // Randomly sorts the students in the class so they are randomly assigned to groups
                            $query2 = "select fname, lname from students where classId=\"".$class['classId']."\" order by rand()";
                            $result2 = $conn->query($query2);

                              // The following will go through the list student by student for each class and then place them
                              // into a group randomly
                            if ($class['approved'] = 1)
                            {
                              while ($studentList = $result2->fetch_assoc())
                              {
                                $s1 = $studentList['fname'].' '.$studentList['lname'];
                                $studentList = $result2->fetch_assoc();
                                $s2 = $studentList['fname'].' '.$studentList['lname'];
                                $studentList = $result2->fetch_assoc();
                                $s3 = $studentList['fname'].' '.$studentList['lname'];
                                $studentList = $result2->fetch_assoc();
                                $s4 = $studentList['fname'].' '.$studentList['lname'];
                                $studentList = $result2->fetch_assoc();
                                $s5 = $studentList['fname'].' '.$studentList['lname'];
                                $insert = "insert into groups values(\"".$groupNum."\", \"".$s1."\", \"".$s2."\", \"".$s3."\", \"".$s4."\", \"".$s5."\", \"".$class['classId']."\")";
                                $conn->query($insert);
                                $groupNum++;
                              }
                              $update = "update classes set approved = 2 where classId=".$class['classId'];
                              $conn->query($update);
                            }
                              // Runs the query to get the groups table
                            $groupsQuery = "select * from groups where classId=\"".$class['classId']."\"";
                            $groupsResult = $conn->query($groupsQuery);

                              // This prints all groups to the page
                            while ($group = $groupsResult->fetch_assoc())
                            {
                              echo '<h3>Group '.$group['groupNum'].'</h3>';
                              echo '<table align="center" style="color:black;" cellpadding="4">';
                              if ($group['s1'] != " ")
                              {
                                echo '<tr><td colspan="2">'.$group['s1'].'</td></tr>';
                              }
                              if ($group['s2'] != " ")
                              {
                                echo '<tr><td colspan="2">'.$group['s2'].'</td></tr>';
                              }
                              if ($group['s3'] != " ")
                              {
                                echo '<tr><td colspan="2">'.$group['s3'].'</td></tr>';
                              }
                              if ($group['s4'] != " ")
                              {
                                echo '<tr><td colspan="2">'.$group['s4'].'</td></tr>';
                              }
                              if ($group['s5'] != " ")
                              {
                                echo '<tr><td colspan="2">'.$group['s5'].'</td></tr>';
                              }
                              echo '</table><br><br>';
                            }
                          }
                        } 
                        else
                        {
                                // If no classes have been approved then the professor is made aware of
                                // that instead of displaying groups
                            echo '<div class="text text-center">';
                            echo '<h2>No classes are currently approved to create groups.</h2>';
                        }

                    ?>

                    </div>
		        </div>
		    </div>
		</div>
	</section>

     <!-- loader -->
  <div id="ftco-loader" class="show fullscreen">
      <svg class="circular" width="48px" height="48px">
          <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
          <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/>
        </svg>
    </div>


  <script src="js/jquery.min.js"></script>
  <script src="js/jquery-migrate-3.0.1.min.js"></script>
  <script src="js/popper.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/jquery.easing.1.3.js"></script>
  <script src="js/jquery.waypoints.min.js"></script>
  <script src="js/jquery.stellar.min.js"></script>
  <script src="js/owl.carousel.min.js"></script>
  <script src="js/jquery.magnific-popup.min.js"></script>
  <script src="js/aos.js"></script>
  <script src="js/jquery.animateNumber.min.js"></script>
  <script src="js/scrollax.min.js"></script>
  <script src="js/main.js"></script>
    
  </body>
</html>